### PR TITLE
migrate from old to new repo

### PR DESCRIPTION
**Pull request by woodenchalet**
# Code review

#### Description
Migrate from [old repo](https://github.com/HaoNiuBi/machine-learning-tutorial) to [new repo](https://github.com/HaoNiuBi/machine_learning_tutorial), with necessary files. Since to change the whole file structure of the old repo, it is easier to migrate the old repo to a new repo. 

#### Task done
- [x] Migrate md files to new repo
- [x] Generate Django file structure

#### Required
@the-friyia @ZacharyLau @RaufHossain

### CODE REVIEW

**Comment by the-friyia** [comment]
Please explain this @woodenchalet

**Comment by woodenchalet** [comment]
Pull request description updated.

**Comment by the-friyia** [comment]
Not really sure how to test this and its probably bad form but lets say +1. If there are any issues with the Django structure they are easy to fix. Go ahead and Merge

**Comment by woodenchalet** [comment]
I will try to figure out how to connect angular.js to Django and update the
markdown.

**Comment by the-friyia** [comment]
You dont need to. Just include Angular.js in the public templates "js" file. I will take care of the rest. I already know how to use it. You dont need to install anything

**Comment by woodenchalet** [comment]
Cool.

**Pull request merged**
